_wandb:
    value:
        cli_version: 0.21.1
        e:
            mgpi8yfzddwa6ncdrnz4zkhs1c75f6ws:
                args:
                    - dataset=cifar10
                    - model=resnet18
                    - batch_norm=True
                    - dropout=True
                    - eval_interval=10
                    - epochs=101
                    - lr=0.1
                    - batch_size=128
                codePath: training_scheme_data_augmentation.py
                codePathLocal: training_scheme_data_augmentation.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "549399085056"
                email: jorneirik@simula.no
                executable: /home/jeb/Projects/training/regularization-using-data/venv/bin/python
                git:
                    commit: 9fa9fbdb31b40711161b896a40af6e58e258e752
                    remote: https://github.com/JornEirikBetten/regularization-using-data.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-379b783d-88eb-a3ab-6321-1a0cbc2521b9
                host: JEB
                memory:
                    total: "16351690752"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/jeb/Projects/training/regularization-using-data/training_scheme_data_augmentation.py
                python: CPython 3.11.5
                root: /home/jeb/Projects/training/regularization-using-data
                startedAt: "2025-08-17T10:42:21.416137Z"
                writerId: mgpi8yfzddwa6ncdrnz4zkhs1c75f6ws
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 45
                - 51
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 45
                - 51
            "3":
                - 13
                - 16
            "4": 3.11.5
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
batch_norm:
    value: true
batch_size:
    value: 128
dataset:
    value: cifar10
dropout:
    value: true
epochs:
    value: 101
eval_interval:
    value: 10
lr:
    value: 0.1
model:
    value: dropoutresnet18
optimizer:
    value: adam
save_model:
    value: true
seed:
    value: 123456
wandb:
    value: true
